import {
  LayoutDashboard,
  Gauge,
  BarChart3,
  Columns3,
  Kanban,
  ListTodo,
  GitBranch,
  Users,
  Building2,
  Shield,
  KeyRound,
  Landmark,
  Receipt,
  Wallet,
  FileSpreadsheet,
  Megaphone,
  FileText,
  MessageSquare,
  Mail,
  Bell,
  Radio,
  History,
  ScrollText,
  Bot,
  Sparkles,
  Wand2,
  Calculator,
  HardDrive,
  Paperclip,
  Settings,
  Plug,
} from "lucide-react";
import { registerCategory, registerModules, navigationRegistry } from "../services/NavigationRegistry";
import type { NavCategory, NavModule } from "../types/navigation";

const CATEGORIES: NavCategory[] = [
  { id: "dashboards", label: "Dashboards", sortOrder: 10, defaultExpanded: true },
  { id: "operations", label: "Operations", sortOrder: 20, defaultExpanded: true },
  { id: "members", label: "Members", sortOrder: 30, defaultExpanded: true },
  { id: "finance", label: "Finance", sortOrder: 40, defaultExpanded: false },
  { id: "communication", label: "Communication", sortOrder: 50, defaultExpanded: false },
  { id: "analytics", label: "Analytics", sortOrder: 60, defaultExpanded: false },
  { id: "automation", label: "Automation", sortOrder: 70, defaultExpanded: false },
  { id: "settings", label: "Settings", sortOrder: 90, defaultExpanded: false },
];

const MODULES: NavModule[] = [
  // ── Dashboards ──
  {
    id: "executive-overview",
    label: "Executive overview",
    route: "/dashboard",
    icon: LayoutDashboard,
    categoryId: "dashboards",
    sortOrder: 10,
    activeMatch: "exact",
    rail: true,
    railOrder: 10,
    keywords: ["home", "overview", "dashboard"],
  },
  {
    id: "role-dashboard",
    label: "My role dashboard",
    route: "/dashboard",
    icon: Gauge,
    categoryId: "dashboards",
    sortOrder: 20,
    visibility: "coming_soon",
    badge: { variant: "soon" },
    keywords: ["role", "tasks"],
  },
  {
    id: "committee-analytics",
    label: "Committee analytics",
    route: "/dashboard",
    icon: BarChart3,
    categoryId: "dashboards",
    sortOrder: 30,
    visibility: "coming_soon",
    badge: { variant: "soon" },
    permissions: { minTier: "LEADERSHIP" },
  },

  // ── Operations ──
  {
    id: "workflow-pipelines",
    label: "Workflow pipelines",
    route: "/dashboard/pipelines",
    icon: Columns3,
    categoryId: "operations",
    sortOrder: 10,
    activeMatch: "prefix",
    rail: true,
    railOrder: 20,
    keywords: ["pipeline", "workflow", "kanban"],
  },
  {
    id: "branch-workflows",
    label: "Branch-wide workflows",
    route: "/dashboard/pipelines",
    icon: GitBranch,
    categoryId: "operations",
    sortOrder: 20,
    visibility: "coming_soon",
    badge: { variant: "soon" },
    permissions: { minTier: "LEADERSHIP" },
  },
  {
    id: "kanban-boards",
    label: "Kanban boards",
    route: "/dashboard/pipelines",
    icon: Kanban,
    categoryId: "operations",
    sortOrder: 30,
    parentId: "workflow-pipelines",
    activeMatch: "none",
    keywords: ["board", "columns"],
  },
  {
    id: "task-assignments",
    label: "Task assignments",
    route: "/dashboard/pipelines",
    icon: ListTodo,
    categoryId: "operations",
    sortOrder: 40,
    parentId: "workflow-pipelines",
    activeMatch: "none",
    keywords: ["tasks", "assign"],
  },

  // ── Members ──
  {
    id: "executive-roster",
    label: "Executive roster",
    route: "/dashboard/members",
    icon: Users,
    categoryId: "members",
    sortOrder: 10,
    activeMatch: "prefix",
    rail: true,
    railOrder: 40,
    keywords: ["members", "people", "roster"],
  },
  {
    id: "branch-units",
    label: "Branch units",
    route: "/dashboard/members",
    icon: Building2,
    categoryId: "members",
    sortOrder: 20,
    activeMatch: "none",
    keywords: ["committee", "chapter", "society"],
  },
  {
    id: "roles-hierarchy",
    label: "Roles & hierarchy",
    route: "/dashboard/members",
    icon: Shield,
    categoryId: "members",
    sortOrder: 30,
    visibility: "coming_soon",
    badge: { variant: "soon" },
    permissions: { minTier: "LEADERSHIP" },
  },
  {
    id: "permission-tiers",
    label: "Permission tiers",
    route: "/dashboard/members",
    icon: KeyRound,
    categoryId: "members",
    sortOrder: 40,
    visibility: "coming_soon",
    badge: { variant: "soon" },
    permissions: { masterOnly: true },
  },

  // ── Finance ──
  {
    id: "budget-finance",
    label: "Budget & finance",
    route: "/dashboard/budget",
    icon: Landmark,
    categoryId: "finance",
    sortOrder: 10,
    activeMatch: "prefix",
    rail: true,
    railOrder: 50,
    keywords: ["budget", "money", "treasurer"],
  },
  {
    id: "transactions",
    label: "Transactions",
    route: "/dashboard/budget",
    icon: Receipt,
    categoryId: "finance",
    sortOrder: 20,
    parentId: "budget-finance",
    activeMatch: "none",
  },
  {
    id: "reimbursements",
    label: "Reimbursements",
    route: "/dashboard/budget",
    icon: Wallet,
    categoryId: "finance",
    sortOrder: 30,
    parentId: "budget-finance",
    activeMatch: "none",
  },
  {
    id: "financial-reports",
    label: "Financial reports",
    route: "/dashboard/budget",
    icon: FileSpreadsheet,
    categoryId: "finance",
    sortOrder: 40,
    visibility: "coming_soon",
    badge: { variant: "soon" },
    permissions: { minTier: "LEADERSHIP" },
  },

  // ── Communication ──
  {
    id: "announcements",
    label: "Announcements",
    route: "/dashboard/communications",
    icon: Megaphone,
    categoryId: "communication",
    sortOrder: 10,
    activeMatch: "prefix",
    rail: true,
    railOrder: 60,
    keywords: ["news", "broadcast"],
  },
  {
    id: "meeting-minutes",
    label: "Meeting minutes",
    route: "/dashboard/communications",
    icon: FileText,
    categoryId: "communication",
    sortOrder: 20,
    activeMatch: "none",
    keywords: ["minutes", "secretary"],
  },
  {
    id: "discussions",
    label: "Discussions",
    route: "/dashboard/communications",
    icon: MessageSquare,
    categoryId: "communication",
    sortOrder: 30,
    activeMatch: "none",
  },
  {
    id: "correspondence",
    label: "Official correspondence",
    route: "/dashboard/communications",
    icon: Mail,
    categoryId: "communication",
    sortOrder: 40,
    visibility: "coming_soon",
    badge: { variant: "soon" },
  },
  {
    id: "in-app-alerts",
    label: "In-app alerts",
    route: "/dashboard/notifications",
    icon: Bell,
    categoryId: "communication",
    sortOrder: 50,
    activeMatch: "prefix",
    rail: true,
    railOrder: 30,
    keywords: ["notifications", "alerts"],
  },
  {
    id: "email-notifications",
    label: "Email notifications",
    route: "/dashboard/notifications",
    icon: Mail,
    categoryId: "communication",
    sortOrder: 60,
    visibility: "coming_soon",
    badge: { variant: "soon" },
  },
  {
    id: "global-broadcasts",
    label: "Global broadcasts",
    route: "/dashboard/notifications",
    icon: Radio,
    categoryId: "communication",
    sortOrder: 70,
    visibility: "coming_soon",
    badge: { variant: "soon" },
    permissions: { minTier: "LEADERSHIP" },
  },

  // ── Analytics ──
  {
    id: "activity-history",
    label: "Activity history",
    route: "/dashboard/notifications",
    icon: History,
    categoryId: "analytics",
    sortOrder: 10,
    visibility: "coming_soon",
    badge: { variant: "soon" },
  },
  {
    id: "audit-logs",
    label: "Audit logs",
    route: "/dashboard/settings",
    icon: ScrollText,
    categoryId: "analytics",
    sortOrder: 20,
    visibility: "coming_soon",
    badge: { variant: "soon" },
    permissions: { masterOnly: true },
  },

  // ── Automation (AI) ──
  {
    id: "ai-assistants",
    label: "AI assistants",
    route: "/dashboard",
    icon: Bot,
    categoryId: "automation",
    sortOrder: 10,
    visibility: "coming_soon",
    badge: { variant: "soon" },
  },
  {
    id: "report-generator",
    label: "Report generator",
    route: "/dashboard",
    icon: Sparkles,
    categoryId: "automation",
    sortOrder: 20,
    visibility: "coming_soon",
    badge: { variant: "soon" },
  },
  {
    id: "email-drafts",
    label: "Email drafts",
    route: "/dashboard",
    icon: Wand2,
    categoryId: "automation",
    sortOrder: 30,
    visibility: "coming_soon",
    badge: { variant: "soon" },
  },
  {
    id: "budget-summaries",
    label: "Budget summaries",
    route: "/dashboard",
    icon: Calculator,
    categoryId: "automation",
    sortOrder: 40,
    visibility: "coming_soon",
    badge: { variant: "soon" },
  },
  {
    id: "google-drive",
    label: "Google Drive",
    route: "/dashboard/settings",
    icon: HardDrive,
    categoryId: "automation",
    sortOrder: 50,
    visibility: "coming_soon",
    badge: { variant: "soon" },
  },
  {
    id: "task-attachments",
    label: "Task attachments",
    route: "/dashboard/pipelines",
    icon: Paperclip,
    categoryId: "automation",
    sortOrder: 60,
    visibility: "coming_soon",
    badge: { variant: "soon" },
  },

  // ── Settings ──
  {
    id: "system-settings",
    label: "System settings",
    route: "/dashboard/settings",
    icon: Settings,
    categoryId: "settings",
    sortOrder: 10,
    activeMatch: "prefix",
    permissions: { masterOnly: true },
    keywords: ["admin", "config"],
  },
  {
    id: "integrations",
    label: "Integrations",
    route: "/dashboard/settings",
    icon: Plug,
    categoryId: "settings",
    sortOrder: 20,
    visibility: "coming_soon",
    badge: { variant: "soon" },
    permissions: { masterOnly: true },
  },
];

export function initIToolsNavigation(): void {
  if (navigationRegistry.isInitialized()) return;
  CATEGORIES.forEach(registerCategory);
  registerModules(MODULES);
  navigationRegistry.markInitialized();
}

export { CATEGORIES, MODULES };
